# -*- coding: utf-8 -*-
"""Movie Recomendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ebu7N2-4eoc7eG3klnPuhC2mUwzjw0w6
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("/content/movies_metadata.csv")

df.head()

df.columns

df.info()

df.shape

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates().reset_index(drop=True)

df.duplicated().sum()

df.columns

df = df[['title','genres','overview','tagline','vote_average','popularity']]

df

df.isnull().sum()

df = df.dropna(subset=['title'])

df['overview'] = df['overview'].fillna('')

df.iloc[0]['genres']

import ast

df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

df.head()

df['tagline'] = df['tagline'].fillna('')

df.isnull().sum()

df['tags']  = df['overview']+ " " + df['genres'] + " " + df['tagline']

df.head()

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
  #lowercase
  text = str(text).lower()

  #remove special characters
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

df['tags'] = df['tags'].apply(preprocess_text)

df['tags'][1]

df = df.reset_index(drop=True)

indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer(max_features=50000, ngram_range=(1,2), stop_words='english')

tfidf_matrix = tfid.fit_transform(df['tags'])

tfidf_matrix

from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n = 10):
  if title not in indices:
    return "Movie not found"

  idx = indices[title]
  sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx  = sim_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

recommend('Toy Story')

import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

pickle.dump(indices, open('indices.pkl', 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfid, open('tfid.pkl', 'wb'))

